FROM debian:stable-slim as deb-adminer-img

LABEL MAINTAINER Ribamar FS <ribafs@gmail.com>

RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

RUN apt-get update && apt-get install -y curl wget gnupg2 ca-certificates lsb-release apt-transport-https
RUN wget https://packages.sury.org/php/apt.gpg
RUN apt-key add apt.gpg
RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php7.list
RUN apt-get update

RUN apt-get update && apt-get install -y nano curl apache2 libapache2-mod-php7.4 php7.4 php7.4-mysql php7.4-pgsql php7.4-pdo-sqlite

WORKDIR /var/www/html

COPY web/index.php /var/www/html
COPY web/perms /usr/local/bin
RUN chmod +x /usr/local/bin/perms

EXPOSE 80

ENTRYPOINT ["/usr/local/bin/perms"]

CMD ["apachectl", "-DFOREGROUND"]
