FROM ubuntu as sqlite-img

LABEL MAINTAINER Ribamar FS <ribafs@gmail.com>

COPY sqlite/setup.sql /

RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

RUN apt-get update && apt-get install -y sqlite3 curl nano


