#!/bin/sh
# sudo adduser ribafs www-data
clear;
echo "Aguarde enquanto configuro as permissões do /var/www/html/$1";
echo "";
find /var/www/html/$1/ -type d -exec chmod 755 {} \;
find /var/www/html/$1/ -type d -exec chmod u+s {} \;
find /var/www/html/$1/ -type f -exec chmod 644 {} \;
chown -R www-data:www-data /var/www/html/$1/
echo "";
echo "Concluído!";
