FROM alpine:edge as alp-web-img

LABEL MAINTAINER Ribamar FS <ribafs@gmail.com>

RUN apk add openrc
RUN ln -sf /sbin/openrc-init /sbin/init
ENTRYPOINT ["/sbin/init"]

RUN apk add apache2 php7-apache2 php7 php7-pdo_mysql

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories

# Add basics first
RUN apk update && apk add bash curl ca-certificates tzdata nano

# Setup apache and php
RUN apk add \
	php7-xdebug \
	php7-mcrypt \
	php7-mbstring \
	php7-pdo \
	php7-zip \
	php7-sqlite3 \
	php7-pdo_pgsql \
	php7-gd \
	php7-pdo_mysql \
	php7-pdo_sqlite \
	php7-xml \
	php7-xmlreader \
	php7-curl \
	php7-intl \
	php7-apcu

# Problems installing in above stack
RUN apk add php7-simplexml

RUN cp /usr/bin/php7 /usr/bin/php && rm -f /var/cache/apk/*

# Add apache to run and configure
RUN sed -i "s/#LoadModule\ rewrite_module/LoadModule\ rewrite_module/" /etc/apache2/httpd.conf \
    && sed -i "s/#LoadModule\ session_module/LoadModule\ session_module/" /etc/apache2/httpd.conf \
    && sed -i "s/#LoadModule\ session_cookie_module/LoadModule\ session_cookie_module/" /etc/apache2/httpd.conf \
    && sed -i "s/#LoadModule\ session_crypto_module/LoadModule\ session_crypto_module/" /etc/apache2/httpd.conf \
    && sed -i "s/#LoadModule\ deflate_module/LoadModule\ deflate_module/" /etc/apache2/httpd.conf \
    && sed -i "s#^DocumentRoot \".*#DocumentRoot \"/app/public\"#g" /etc/apache2/httpd.conf \
    && sed -i "s#/var/www/localhost/htdocs#/app/public#" /etc/apache2/httpd.conf \
    && printf "\n<Directory \"/app/public\">\n\tAllowOverride All\n</Directory>\n" >> /etc/apache2/httpd.conf

RUN mkdir /app && mkdir /app/public && chown -R apache:apache /app && chmod -R 755 /app

COPY web/index.php /app/public
COPY web/connection.php /app/public
COPY web/perms /usr/local/bin
RUN chmod +x /usr/local/bin/perms

RUN chown -R apache:apache /app/public
RUN chmod -R 755 /app/public

WORKDIR ["/app/public"]

EXPOSE 80

VOLUME [ “/sys/fs/cgroup” ]

