FROM alpine:edge as php-img

LABEL MAINTAINER Ribamar FS <ribafs@gmail.com>

RUN apk add openrc
RUN ln -sf /sbin/openrc-init /sbin/init
ENTRYPOINT ["/sbin/init"]
WORKDIR /var/www/htdocs

RUN apk add php7 php7-pdo_mysql

# Add basics first
RUN apk update && apk add tzdata nano

EXPOSE 80

VOLUME [ “/sys/fs/cgroup” ]

