version: "3.6" 
services:
    postgres:
      container_name: postgres-container
      restart: always
      build:
        context: .
        dockerfile: ./Dockerfile-postgres
      ports:
        - "6432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
      tty: true
    networks:
      - alpine-net

    web:
      container_name: web-container
      build:
        context: .
        dockerfile: Dockerfile-web
      volumes:
        - ./web:/var/www/html
      ports:
        - "8888:80"
    networks:
      - alpine-net

    sqlite:
      container_name: sqlite-container
      restart: always
      build:
        context: .
        dockerfile: ./Dockerfile-sqlite
      volumes:
        - ./sqlite:/var/lib/sqlite
      tty: true
    networks:
      - alpine-net

    adminer:
      container_name: adminer-container
      build:
        context: .
        dockerfile: Dockerfile-adminer
      volumes:
        - ./adminer:/var/www/html
    networks:
      - alpine-net

networks:
  alpine-net:
    driver: bridge

volumes:
  pgdata: {}
  web:
  sqlite:
  adminer:
# Executar: composer: 
# docker-compose down -v
# docker-compose up -d 

