FROM ubuntu:20.04 as postgres-img

LABEL maintainer="Ribamar FS <ribafs@gmail.com>"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y
RUN apt-get update && apt-get install -y postgresql-client postgresql nano

RUN apt-get install -y curl

ADD pg/ /

EXPOSE 5432
