FROM alpine:edge as adminer-img

LABEL maintainer="Milan Sulc <sulcmil@gmail.com>"

# OpenRC
RUN apk add openrc
RUN ln -sf /sbin/openrc-init /sbin/init
ENTRYPOINT ["/sbin/init"]

ENV ADMINER_DG_VERION=1.21.0
ENV MEMORY=256M
ENV UPLOAD=2048M
ENV WDIR=/app/public
WORKDIR $WDIR

RUN apk update && apk add wget ca-certificates apache2 php7-apache2 php7 php7-session php7-pdo_mysql php7-json

RUN	wget https://github.com/dg/adminer-custom/archive/v$ADMINER_DG_VERION.tar.gz -O $WDIR/adminer.tgz && \
    tar zxvf $WDIR/adminer.tgz --strip-components=1 -C $WDIR && \
    rm $WDIR/adminer.tgz && \
    apk del wget ca-certificates && \
    rm -rf /var/cache/apk/*

# Add apache to run and configure
RUN sed -i "s/#LoadModule\ rewrite_module/LoadModule\ rewrite_module/" /etc/apache2/httpd.conf \
    && sed -i "s/#LoadModule\ session_module/LoadModule\ session_module/" /etc/apache2/httpd.conf \
    && sed -i "s/AllowOverride none/AllowOverride All/" /etc/apache2/httpd.conf \
    && sed -i "s/AllowOverride None/AllowOverride All/" /etc/apache2/httpd.conf \
    && sed -i "s/#LoadModule\ session_cookie_module/LoadModule\ session_cookie_module/" /etc/apache2/httpd.conf \
    && sed -i "s/#LoadModule\ session_crypto_module/LoadModule\ session_crypto_module/" /etc/apache2/httpd.conf \
    && sed -i "s/#LoadModule\ deflate_module/LoadModule\ deflate_module/" /etc/apache2/httpd.conf

RUN echo "ServerName localhost" >> /etc/apache2/httpd.conf

ENV WDIR /var/www/localhost/htdocs

WORKDIR $WDIR

# Add basics first
RUN apk update && apk add curl ca-certificates tzdata nano

RUN chown -R apache:apache $WDIR && chmod -R 755 $WDIR

EXPOSE 80

VOLUME [ “/sys/fs/cgroup” ]

CMD /usr/bin/php \
    -d memory_limit=$MEMORY \
    -d upload_max_filesize=$UPLOAD \
    -d post_max_size=$UPLOAD \
    -S 0.0.0.0:80

COPY ["apache/perms", "/usr/local/bin"]
RUN ["chmod", "+x", "/usr/local/bin/perms"]

