FROM alpine:edge as maria-img

LABEL maintainer="Dominic Taylor <dominic@yobasystems.co.uk>"

# OpenRC
RUN apk add openrc
RUN ln -sf /sbin/openrc-init /sbin/init
ENTRYPOINT ["/sbin/init"]

RUN apk add --no-cache mariadb mariadb-client mariadb-server-utils pwgen nano && \
    rm -f /var/cache/apk/*

COPY maria/setup.sql /
COPY maria/my.cnf /etc

EXPOSE 3306

VOLUME ["/var/lib/mysql"]

