FROM alpine:edge as apache-img

LABEL MAINTAINER Ribamar FS <ribafs@gmail.com>

RUN apk add openrc
RUN ln -sf /sbin/openrc-init /sbin/init
ENTRYPOINT ["/sbin/init"]

RUN apk update && apk add apache2 php7-apache2

# Add apache to run and configure
RUN sed -i "s/#LoadModule\ rewrite_module/LoadModule\ rewrite_module/" /etc/apache2/httpd.conf \
    && sed -i "s/#LoadModule\ session_module/LoadModule\ session_module/" /etc/apache2/httpd.conf \
    && sed -i "s/AllowOverride none/AllowOverride All/" /etc/apache2/httpd.conf \
    && sed -i "s/AllowOverride None/AllowOverride All/" /etc/apache2/httpd.conf \
    && sed -i "s/#LoadModule\ session_cookie_module/LoadModule\ session_cookie_module/" /etc/apache2/httpd.conf \
    && sed -i "s/#LoadModule\ session_crypto_module/LoadModule\ session_crypto_module/" /etc/apache2/httpd.conf \
    && sed -i "s/#LoadModule\ deflate_module/LoadModule\ deflate_module/" /etc/apache2/httpd.conf

RUN echo "ServerName localhost" >> /etc/apache2/httpd.conf

ENV WDIR /var/www/localhost/htdocs

WORKDIR $WDIR

COPY ["apache/perms", "/usr/local/bin"]
RUN ["chmod", "+x", "/usr/local/bin/perms"]


# Add basics first
RUN apk update && apk add curl ca-certificates tzdata nano

RUN chown -R apache:apache $WDIR && chmod -R 755 $WDIR

EXPOSE 80

VOLUME [ “/sys/fs/cgroup” ]

