version: "3.6" 

services:
    lamp:
      container_name: docker-lamp
      build:
        context: .
        dockerfile: php/${PHPVERSION}/Dockerfile
      environment:
        APACHE_RUN_USER: www-data
        APACHE_RUN_GROUP: www-data
        WEB_DOCUMENT_ROOT: /var/www/html
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: crud
        MYSQL_USER: crudu
        MYSQL_PASSWORD: crudu

      volumes:
        - ./web:/var/www/html
        - ./mysql:/var/lib/mysql

      ports:
        - "8888:80"
        - "3333:3306"

volumes:
  web:
  mysql:

