
RUN apk update && apk add apache2 php7-apache2  && rm -f /var/cache/apk/* \
    && mkdir /run/apache2 \
    && mkdir -p /opt/utils  

ENV WORKD /var/www/localhost/htdocs
WORKDIR $WORKD
RUN chown -R apache:apache $WORKD
RUN chmod -R 755 $WORKD

# https://httpd.apache.org/docs/2.4/stopping.html#gracefulstop
STOPSIGNAL SIGWINCH

COPY httpd-foreground /usr/local/bin/

EXPOSE 80
CMD ["httpd-foreground"]

VOLUME [ “/sys/fs/cgroup” ]
